#!/bin/bash
echo "postinst $*"

APP={{ application }}
ERL_ROOT={{ target_root }}

case "$1" in
	configure)
	tar xzvf $ERL_ROOT/debian/applications/$APP -C $ERL_ROOT
	truncate -s 0 $ERL_ROOT/debian/applications/$APP
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
