#!/bin/bash

APP={{ application }}
ERL_ROOT={{ target_root }}

case "$1" in
	configure)

    tar xzvf $ERL_ROOT/debian/applications/$APP -C $ERL_ROOT > /dev/null
    truncate -s 0 $ERL_ROOT/debian/applications/$APP

    ;;
esac

exit 0
