#!/bin/bash
#
# This script prepares a set of nodes in 'rel' directory that is used as
# a source of files to be put in debian packages.
#
# This script generates:
# rel/beagle-1      a node with release version 1
# rel/beagle        a node with release version 2
# rel/beagle-full   a node with both releases unpacked (but version 2
#                   not set up) + proper appups and relup in version 2
#

cd `dirname $0`
rm -rf rel/beagle{,-1,-full}
./switch 1 1.0
make
cp -r rel/beagle rel/beagle-full
mv rel/beagle rel/beagle-1
./switch 2 2.0
make
./rebar generate-appups previous_release=beagle-1
./rel/genrelup beagle rel/beagle:2 rel/beagle-1:1 rel/beagle-1:1
cp -rf rel/beagle/releases/2 rel/beagle-full/releases
cp -rf rel/beagle/lib/sampleapp-2.0 rel/beagle-full/lib

